#ddev-generated
services:
  web:
    external_links:
      - "ddev-router:matomo.${DDEV_SITENAME}.${DDEV_TLD}"
  matomo:
    image: matomo:latest
    container_name: ddev-${DDEV_SITENAME}-matomo
    environment:
      HTTPS_EXPOSE: 443:80
      HTTP_EXPOSE: 80
      VIRTUAL_HOST: matomo.$DDEV_HOSTNAME
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_USERNAME: db
      MATOMO_DATABASE_PASSWORD: db
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_DATABASE_TABLES_PREFIX: ""
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    external_links:
      - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
    volumes:
      # Persist configuration and plugin data (GeoIP DB etc.)
      - ./matomo/config:/var/www/html/config
      - ./matomo/misc:/var/www/html/misc
