#ddev-generated
# DDEV Matomo Add-on
# 
# To customize Matomo configuration, create .ddev/config.matomo.yaml
# See https://github.com/madsnorgaard/ddev-matomo for documentation

services:
  web:
    external_links:
      - "ddev-router:matomo.${DDEV_SITENAME}.${DDEV_TLD}"
  
  matomo:
    # Matomo version can be configured during installation or by editing this file
    # Default: "5" (latest Matomo 5.x)
    # To change version: edit this line and run 'ddev restart'
    # Options: "5", "4", "5.1.2", "4.15.1", etc.
    image: matomo:5
    container_name: ddev-${DDEV_SITENAME}-matomo
    environment:
      # DDEV routing configuration
      HTTPS_EXPOSE: 443:80
      HTTP_EXPOSE: 80
      VIRTUAL_HOST: matomo.$DDEV_HOSTNAME
      
      # Database configuration
      # Uses separate database to avoid conflicts with application database
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_USERNAME: db
      MATOMO_DATABASE_PASSWORD: db
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      
      # PHP configuration
      PHP_MEMORY_LIMIT: 256M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_POST_MAX_SIZE: 16M
      PHP_UPLOAD_MAX_FILESIZE: 16M
      
      # Matomo configuration
      MATOMO_GENERAL_ENABLE_TRUSTED_HOST_CHECK: 0
      MATOMO_GENERAL_ASSUME_SECURE_PROTOCOL: 1
      MATOMO_GENERAL_ENABLE_BROWSER_ARCHIVING_TRIGGERING: 1
    
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    
    external_links:
      - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
    
    volumes:
      # Persist essential Matomo data across container restarts
      - ./matomo/config:/var/www/html/config
      - ./matomo/misc:/var/www/html/misc
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/matomo.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
