#ddev-generated
version: '3.6'
services:
  matomo:
    image: matomo:latest
    container_name: ddev-${DDEV_SITENAME}-matomo
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_USERNAME: db
      MATOMO_DATABASE_PASSWORD: db
      MATOMO_DATABASE_DBNAME: db
    ports:
      - "8080:80"
