#ddev-generated
services:
  matomo:
    image: matomo:latest
    container_name: ddev-${DDEV_SITENAME}-matomo
    environment:
      HTTPS_EXPOSE: 443:80
      HTTP_EXPOSE: 80
      VIRTUAL_HOST: matomo.$DDEV_HOSTNAME
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_USERNAME: db
      MATOMO_DATABASE_PASSWORD: db
      MATOMO_DATABASE_DBNAME: matomo
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    external_links:
      - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
